export const keywordOptions = [
  { value: "Real Estate", label: "Real Estate" },
  { value: "Property", label: "Property" },
  { value: "Buying", label: "Buying" },
  { value: "Selling", label: "Selling" },
  { value: "Renting", label: "Renting" },
  { value: "New Home", label: "New Home" },
  { value: "Tourism", label: "Tourism" },
  { value: "Investment", label: "Investment" },
  { value: "Investor", label: "Investor" },
  { value: "Home", label: "Home" },
  { value: "Foreclosure", label: "Foreclosure" },
  { value: "Agent", label: "Agent" },
  { value: "Broker", label: "Broker" },
  { value: "Realtor", label: "Realtor" },
  { value: "Realty", label: "Realty" },
  { value: "Listing", label: "Listing" },
];

export const toneOptions = [
  { label: "😊 Friendly", value: "Friendly" },
  { label: "💎 Luxury", value: "Luxury" },
  { label: "🤩 Excited", value: "Excited" },
  { label: "💰 Sales", value: "Sales" },
  { label: "⛺ Adventurous", value: "Adventurous" },
  { label: "🤓 Informative", value: "Informative" },
  { label: "🤯 Shocking", value: "Shocking" },
  { label: "💼 Professional", value: "Professional" },
  { label: "🤔 Neutral", value: "Neutral" },
  { label: "💪 Bold", value: "Bold" },
  { label: "💡 Witty", value: "Witty" },
  { label: "🧠 Persuasive", value: "Persuasive" },
];
